# -*- coding: utf-8 -*-
"""AI 整改邮件生成（原生AI功能·任务书第2节）。

生成可直接发送给供应商/货代的中英双语邮件草稿：
结构 = 问题概述 → 具体差异点列表 → 需对方确认/补充的内容 → 期望回复时间。

诚实性说明：
  - 配置 API Key 时由 LLM 实时生成完整商务邮件（mode="live"）；
  - 无 Key 时降级为**结构化模板草稿**（mode="offline_template"）——
    内容由本批次真实 FAIL/WARNING 明细数据填充（非通用空模板），
    页面明确标注"离线模板模式：配置API Key后由LLM生成完整商务邮件"；
  - 全部 PASS 的批次不生成（提示"无需生成整改邮件"），不硬造空邮件。
"""

from __future__ import annotations

import json

from llm_endpoint import resolve_endpoint
from verification_engine import run_verification  # noqa: F401  (便于测试直接构造)

REQUEST_TIMEOUT = 60

EMAIL_PROMPT = (
    "你是外贸单证专员，需要根据单证核验结果给供应商/货代写一封要求整改确认的邮件草稿。"
    "要求：\n"
    "1. 分别输出中文版和英文版（用标记 ===中文=== 和 ===English=== 分隔）；\n"
    "2. 结构包含：问题概述、具体差异点列表（引用真实数值，如发票480箱vs报关单475箱）、"
    "需对方确认或补充的内容、期望回复时间（2个工作日内）；\n"
    "3. 语气专业克制、对事不对人，不夸大后果；\n"
    "4. 落款用占位符 [发件人姓名/公司]；\n"
    "5. 每个差异点都必须与下面提供的核验明细一一对应，不要添加不存在的 问题。\n\n"
    "【核验明细】\n{details}\n\n【涉及的单证与字段】\n{fields}"
)


def _collect_problems(verification: dict) -> list[dict]:
    return [r for r in verification["results"] if r["status"] in ("FAIL", "WARNING")]


def _details_text(verification: dict) -> str:
    lines = []
    for r in _collect_problems(verification):
        lines.append(f"- [{r['status']}] {r['check_name']}：{r['detail']}")
    return "\n".join(lines) or "（无）"


def _fields_text(verification: dict, documents: list) -> str:
    lines = []
    for d in documents:
        lines.append(f"- {d.get('doc_type')} ({d.get('doc_id')}): "
                     + json.dumps(d.get("fields", {}), ensure_ascii=False)[:300])
    return "\n".join(lines)


# ---------------------------------------------------------------- 离线模板


def _template_email(verification: dict, lang: str) -> str:
    problems = _collect_problems(verification)
    risk = verification["risk"]

    if lang == "zh":
        issue_lines = "\n".join(
            f"  {i}. [{p['status']}] {p['check_name']}：{p['detail']}" for i, p in enumerate(problems, 1))
        action_lines = "\n".join(
            f"  {i}. {p.get('suggestion') or '请核对并确认该字段。'}" for i, p in enumerate(problems, 1))
        return f"""主题：【单证核验整改确认】{verification.get('batch_name', '本批次')} —— 发现{len(problems)}项需处理事项（风险分 {risk['score']}/100，{risk['grade_label']}）

尊敬的供应商/货代：

我司在发运前单证交叉核验中发现以下问题（风险评分 {risk['score']}/100，{risk['grade_label']}），请协助确认并回复：

一、具体差异点
{issue_lines}

二、需要贵方确认或补充的内容
{action_lines}

请于 2 个工作日内 回复确认上述事项及修正后的单证版本；涉及数值差异的请附称重记录/装箱计数等凭证。为避免口岸滞留产生的额外费用，请务必在货物发运前完成整改。

盼复。

[发件人姓名/公司]
（本邮件草稿由单证核验系统基于核验明细自动生成，发送前请人工审阅）
"""
    issue_lines = "\n".join(
        f"  {i}. [{p['status']}] {p['check_name']}: {p['detail']}" for i, p in enumerate(problems, 1))
    action_lines = "\n".join(
        f"  {i}. {(p.get('suggestion') or 'Please verify and confirm this field.')}" for i, p in enumerate(problems, 1))
    return f"""Subject: [Document Verification Action Required] {verification.get('batch_name', 'This shipment')} - {len(problems)} issue(s) found (Risk score {risk['score']}/100, {risk['grade_label']})

Dear Supplier / Freight Forwarder,

Our pre-shipment cross-verification of shipping documents identified the following issues (risk score {risk['score']}/100, {risk['grade_label']}):

1. Details of discrepancies
{issue_lines}

2. Actions required from your side
{action_lines}

Kindly confirm the above items and return the corrected document versions within 2 working days. For numerical discrepancies, please attach supporting records (weighbridge tickets / packing counts). Completion before dispatch is essential to avoid border detention costs.

Best regards,

[Sender Name / Company]
(This draft was auto-generated by the document verification system based on verification details; please review before sending.)
"""


# ---------------------------------------------------------------- 主入口


def generate_email(verification: dict, documents: list) -> dict:
    """
    返回 {mode, zh, en} 或 {mode: "not_needed"}（全部通过时）。
    """
    if not _collect_problems(verification):
        return {"mode": "not_needed",
                "message": "本批次全部检查通过，无需生成整改邮件。"}

    zh_tpl, en_tpl = _template_email(verification, "zh"), _template_email(verification, "en")
    endpoint = resolve_endpoint()
    if endpoint is None:
        return {"mode": "offline_template", "zh": zh_tpl, "en": en_tpl}

    import urllib.request
    prompt = EMAIL_PROMPT.format(details=_details_text(verification),
                                 fields=_fields_text(verification, documents))
    body = json.dumps({
        "model": endpoint["model"],
        "messages": [{"role": "user", "content": prompt}],
        "temperature": 0.3,
    }).encode("utf-8")
    req = urllib.request.Request(
        f"{endpoint['base_url'].rstrip('/')}/chat/completions",
        data=body,
        headers={"Authorization": f"Bearer {endpoint['api_key']}",
                 "Content-Type": "application/json"})
    try:
        with urllib.request.urlopen(req, timeout=REQUEST_TIMEOUT) as resp:
            content = json.loads(resp.read().decode("utf-8"))["choices"][0]["message"]["content"]
        zh, en = _split_bilingual(content)
        return {"mode": "live", "zh": zh, "en": en}
    except Exception:
        # 实时生成失败 → 降级模板，保证功能可用
        return {"mode": "offline_template", "zh": zh_tpl, "en": en_tpl}


def _split_bilingual(content: str) -> tuple[str, str]:
    """把LLM输出的 ===中文===/===English=== 双段拆开；缺标记时整体作中文。"""
    import re
    m = re.search(r"={2,}\s*(中文|Chinese|ZH)\s*={2,}(.*?)={2,}\s*(English|EN|英文)\s*={2,}(.*)",
                  content, re.S | re.I)
    if m:
        return m.group(2).strip(), m.group(4).strip()
    return content.strip(), ""
